name: 'Synchronize teams to GitHub'
description: 'Read team membership/permissions from YAML and make changes on GH as necessary'

inputs:
  token:
    description: 'A Github personal authentication token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Sync teams
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: >-
        python -m pip install pyyaml requests;
        python ${{ github.action_path }}/sync-teams-to-gh.py -m >> $GITHUB_STEP_SUMMARY
