name: 'Synchronize teams to GitHub'
description: 'Read team membership/permissions from YAML and make changes on GH as necessary'

inputs:
  token:
    description: 'A Github personal authentication token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Sync teams
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: >-
        pip install pyyaml requests;
        python ${{ github.action_path }}/sync-teams-to-gh.py >> $GITHUB_STEP_SUMMARY
